chore: upgraded all packages, removed travis for GitHub actions.
Upgraded to the latest TypeScript: `4.1.2`. Changed all `interface` to
`type` where possible.

Added `jest` and 'react to the `eslintrc`. Also the `lint` script will
now lint the test directory as well. Fixed issues coming out of the
new lint rules.

Added `dev:publish` script which allows local installation of the
package without actually publishing to NPM.

Added `jest-watch-typeahead` for easier searching when running jest in
interactive mode.

There is a breaking change in this version but only for users which
test flash-messages as part of a unit test. Before we told users to test
using: `jest.spyOn(reactFlashMessages, 'addSuccess');`. This will no
longer work and cause a `TypeError during Jest's spyOn: Cannot set
property getRequest of #<Object> which has only a getter` error. A
simple solution is to mock the entire library.

When using Jest you can do in the `setupTests.ts` file:

```ts
// Mock @42.nl/react-flash-messages
jest.mock('@42.nl/react-flash-messages', () => {
  const originalModule = jest.requireActual('@42.nl/react-flash-messages');

  return {
    ...originalModule,
    addError: jest.fn(),
    addWarning: jest.fn(),
    addSuccess: jest.fn(),
    addInfo: jest.fn(),
    addApocalypse: jest.fn(),
    removeFlashMessage: jest.fn()
  }
});
```

This way by default all flash messages are mocked, and there is no need
to do `jest.spyOn(reactFlashMessages, 'addSuccess');` again.